replicaCount: 2

image:
  repository: 182399705651.dkr.ecr.us-east-1.amazonaws.com/skyfire-api
  tag: "0.1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  className: alb
  host: skyfire.fabdev.co
  path: /
  certificateArn: arn:aws:acm:us-east-1:182399705651:certificate/a3c955e8-56f1-4cb1-a800-94f116af0ad4
  healthCheck:
    path: /health/ready
    successCodes: "200"

health:
  livenessPath: /health/live
  readinessPath: /health/ready

rollout:
  minReadySeconds: 5
  progressDeadlineSeconds: 300
  maxUnavailable: 0
  maxSurge: 1

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "250m"
    memory: "256Mi"
